[build]
publish = "site/"
command = """
pip3 install -q poetry &&
poetry install &&
poetry run mkdocs build &&
cp src/_redirects site/_redirects &&
cp httpemojicodes/emojicodes.json site/api/codes.json
"""

[[headers]]
  for = "/*"
  [headers.values]
    X-Status-Emoji = ":thumsup:"

[[headers]]
  for = "/404.html"
  [headers.values]
    X-Status-Emoji = ":woman_shrugging:"
