[build]
publish = "site/"
command = """
mkdocs build &&
cp mkdocs/_redirects site/_redirects
"""

[[headers]]
for = "/*"
[headers.values]
  X-Status-Emoji = ":thumsup:"
for = "/404.html"
[headers.values]
  X-Status-Emoji = ":woman_shrugging:"
