[build]
publish = "site/"
command = """
pip3 install -q poetry &&
poetry config settings.virtualenvs.in-project true &&
poetry install &&
poetry run mkdocs build
"""

[[headers]]
for = "/*"
[headers.values]
  X-Status-Emoji = ":thumsup:"
for = "/404.html"
[headers.values]
  X-Status-Emoji = ":woman_shrugging:"
